
name: Bocchi OS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. ОЧИСТКА МЕСТА (Освобождаем ~100ГБ)
      - name: Cleanup and Free Space
        run: |
          sudo docker image prune -a -f
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "/usr/local/share/powershell"
          sudo rm -rf "/usr/local/lib/node_modules"
          df -h

      # 2. УСТАНОВКА REPO
      - name: Install Repo
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      # 3. ИНИЦИАЛИЗАЦИЯ И СИНХРОНИЗАЦИЯ (Облегченная версия)
      - name: Initialize and Sync
        run: |
          git config --global user.email "bocchi@os.com"
          git config --global user.name "Bocchi"
          
          # Проверяем свободное место перед стартом
          df -h
          
          # Чистим старое
          rm -rf .repo
          
          # Инициализация без лишнего мусора (depth=1 экономит кучу места)
          repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --depth=1
          
          # Твой манифест
          mkdir -p .repo/local_manifests
          curl -L https://raw.githubusercontent.com/yessaimon/bocchi_os/main/manifest.xml > .repo/local_manifests/bocchi.xml
          
          # Синхронизация в 4 потока (самый стабильный вариант)
          repo sync -c -j4 --force-sync --no-tags --current-branch --no-clone-bundle

      # 4. ПОДГОТОВКА СБОРКИ
      - name: Setup Build Environment
        run: |
          source build/envsetup.sh
          lunch lineage_sapphire-userdebug

      # 5. СТАРТ КОМПИЛЯЦИИ
      - name: Build Bocchi OS
        run: |
          source build/envsetup.sh
          mka bacon -j$(nproc --all)
